// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjbgvygziiuzyouwejsd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqYmd2eWd6aWl1enlvdXdlanNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NDIzNDgsImV4cCI6MjA3MTAxODM0OH0.7P8txn77TvfNKYA-etCJENpDSucfzu8X3ZaxkpcXMgw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});